/**
 * GERADO POR `scripts/build-exercise-index.mjs` — NÃO EDITAR À MÃO.
 * Fonte: free-exercise-db (Unlicense, ADR-004). Regenerar com:
 *   node scripts/build-exercise-index.mjs [exercises.json]
 *
 * Cada núcleo de movimento lista as variações do catálogo que têm foto, com as tags
 * derivadas do equipamento e do nome em inglês. O resolvedor (`exerciseMedia.ts`)
 * escolhe dentro do núcleo pela sobreposição de tags com o nome PT-BR do plano.
 */

/** [id no free-exercise-db, tags PT-BR da variação] */
export type IndexedVariant = readonly [string, readonly string[]];

export const EXERCISE_INDEX: Record<string, readonly IndexedVariant[]> = {
  abdominal: [
    ["3_4_Sit-Up", ["livre"]],
    ["Ab_Crunch_Machine", ["maquina", "supinada"]],
    ["Bosu_Ball_Cable_Crunch_With_Side_Bends", ["cabo", "lateral"]],
    ["Cable_Crunch", ["cabo"]],
    ["Cable_Reverse_Crunch", ["cabo"]],
    ["Cable_Seated_Crunch", ["cabo", "sentado"]],
    ["Cross-Body_Crunch", ["livre"]],
    ["Crunch_-_Hands_Overhead", ["livre"]],
    ["Crunch_-_Legs_On_Exercise_Ball", ["livre"]],
    ["Crunches", ["livre"]],
    ["Decline_Crunch", ["declinado", "livre"]],
    ["Decline_Oblique_Crunch", ["declinado", "livre"]],
    ["Decline_Reverse_Crunch", ["declinado", "livre"]],
    ["Exercise_Ball_Crunch", ["bola"]],
    ["Frog_Sit-Ups", ["livre"]],
    ["Gorilla_Chin_Crunch", ["livre", "supinada"]],
    ["Jackknife_Sit-Up", ["livre"]],
    ["Janda_Sit-Up", ["livre"]],
    ["Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists", ["cabo", "unilateral"]],
    ["Oblique_Crunches", ["livre"]],
    ["Oblique_Crunches_-_On_The_Floor", ["livre"]],
    ["Press_Sit-Up", ["barra"]],
    ["Reverse_Crunch", ["livre"]],
    ["Rope_Crunch", ["cabo", "corda"]],
    ["Sit-Up", ["livre"]],
    ["Standing_Rope_Crunch", ["cabo", "corda", "empe"]],
    ["Suspended_Reverse_Crunch", ["outro", "suspenso"]],
    ["Tuck_Crunch", ["livre"]],
    ["Weighted_Crunches", ["bola"]],
    ["Weighted_Sit-Ups_-_With_Bands", ["outro"]],
  ],
  abdutora: [
    ["Thigh_Abductor", ["maquina"]],
  ],
  adutora: [
    ["Thigh_Adductor", ["maquina"]],
  ],
  afundo: [
    ["Barbell_Lunge", ["barra"]],
    ["Barbell_Step_Ups", ["barra"]],
    ["Barbell_Walking_Lunge", ["barra"]],
    ["Bodyweight_Walking_Lunge", ["outro"]],
    ["Dumbbell_Lunges", ["halteres"]],
    ["Dumbbell_Rear_Lunge", ["halteres"]],
    ["Dumbbell_Step_Ups", ["halteres"]],
    ["Elevated_Back_Lunge", ["barra"]],
    ["Kettlebell_Turkish_Get-Up_Lunge_style", ["kettlebell"]],
    ["Lunge_Pass_Through", ["kettlebell"]],
    ["Lunge_Sprint", ["maquina"]],
    ["Step-up_with_Knee_Raise", ["livre"]],
  ],
  agachamento: [
    ["Barbell_Full_Squat", ["barra"]],
    ["Barbell_Hack_Squat", ["barra"]],
    ["Barbell_Side_Split_Squat", ["barra", "bulgaro", "lateral"]],
    ["Barbell_Squat", ["barra"]],
    ["Barbell_Squat_To_A_Bench", ["barra"]],
    ["Bodyweight_Squat", ["livre"]],
    ["Box_Squat", ["barra"]],
    ["Box_Squat_with_Bands", ["barra"]],
    ["Box_Squat_with_Chains", ["barra"]],
    ["Chair_Squat", ["maquina"]],
    ["Dumbbell_Squat", ["halteres"]],
    ["Dumbbell_Squat_To_A_Bench", ["halteres"]],
    ["Frankenstein_Squat", ["barra"]],
    ["Freehand_Jump_Squat", ["livre"]],
    ["Front_Barbell_Squat", ["barra"]],
    ["Front_Barbell_Squat_To_A_Bench", ["barra"]],
    ["Front_Squat_Clean_Grip", ["barra", "frontal"]],
    ["Front_Squats_With_Two_Kettlebells", ["frontal", "kettlebell"]],
    ["Goblet_Squat", ["goblet", "kettlebell"]],
    ["Hack_Squat", ["maquina"]],
    ["Jefferson_Squats", ["barra"]],
    ["Kettlebell_Pistol_Squat", ["kettlebell"]],
    ["Kettlebell_Turkish_Get-Up_Squat_style", ["kettlebell"]],
    ["Kneeling_Jump_Squat", ["barra"]],
    ["Kneeling_Squat", ["barra"]],
    ["Lying_Machine_Squat", ["deitado", "maquina", "supinada"]],
    ["Narrow_Stance_Hack_Squats", ["maquina"]],
    ["Narrow_Stance_Squats", ["barra"]],
    ["Olympic_Squat", ["barra"]],
    ["One_Leg_Barbell_Squat", ["barra", "unilateral"]],
    ["One-Arm_Overhead_Kettlebell_Squats", ["kettlebell", "unilateral"]],
    ["Overhead_Squat", ["barra"]],
    ["Plie_Dumbbell_Squat", ["halteres"]],
    ["Reverse_Band_Box_Squat", ["barra"]],
    ["Reverse_Band_Power_Squat", ["barra"]],
    ["Single-Leg_High_Box_Squat", ["outro", "unilateral"]],
    ["Smith_Machine_Pistol_Squat", ["maquina", "smith", "supinada"]],
    ["Smith_Machine_Squat", ["maquina", "smith", "supinada"]],
    ["Smith_Single-Leg_Split_Squat", ["bulgaro", "maquina", "smith", "unilateral"]],
    ["Speed_Box_Squat", ["barra"]],
    ["Speed_Squats", ["barra"]],
    ["Split_Squat_with_Dumbbells", ["bulgaro", "halteres"]],
    ["Squat_Jerk", ["barra"]],
    ["Squat_with_Bands", ["barra"]],
    ["Squat_with_Chains", ["barra"]],
    ["Squat_with_Plate_Movers", ["anilha", "barra"]],
    ["Squats_-_With_Bands", ["elastico"]],
    ["Suspended_Split_Squat", ["bulgaro", "outro", "suspenso"]],
    ["Weighted_Jump_Squat", ["barra"]],
    ["Weighted_Sissy_Squat", ["barra"]],
    ["Weighted_Squat", ["outro"]],
    ["Wide_Stance_Barbell_Squat", ["barra"]],
    ["Zercher_Squats", ["barra"]],
  ],
  barra_fixa: [
    ["Band_Assisted_Pull-Up", ["outro"]],
    ["Chin-Up", ["livre", "supinada"]],
    ["One_Arm_Chin-Up", ["outro", "supinada", "unilateral"]],
    ["Pullups", ["livre"]],
    ["Scapular_Pull-Up", ["outro"]],
    ["V-Bar_Pullup", ["livre"]],
    ["Weighted_Pull_Ups", ["outro"]],
    ["Wide-Grip_Rear_Pull-Up", ["aberta", "livre"]],
  ],
  crossover: [
    ["Cable_Crossover", ["cabo"]],
    ["Low_Cable_Crossover", ["cabo"]],
    ["Single-Arm_Cable_Crossover", ["cabo"]],
  ],
  crucifixo: [
    ["Back_Flyes_-_With_Bands", ["elastico"]],
    ["Bodyweight_Flyes", ["barraw"]],
    ["Decline_Dumbbell_Flyes", ["declinado", "halteres"]],
    ["Dumbbell_Flyes", ["halteres"]],
    ["Flat_Bench_Cable_Flyes", ["cabo"]],
    ["Incline_Cable_Flye", ["cabo", "inclinado"]],
    ["Incline_Dumbbell_Flyes", ["halteres", "inclinado"]],
    ["Incline_Dumbbell_Flyes_-_With_A_Twist", ["halteres", "inclinado"]],
    ["One-Arm_Flat_Bench_Dumbbell_Flye", ["halteres", "unilateral"]],
  ],
  crucifixo_inverso: [
    ["Barbell_Rear_Delt_Row", ["barra"]],
    ["Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench", ["curvado", "halteres"]],
    ["Cable_Rear_Delt_Fly", ["cabo"]],
    ["Lying_Rear_Delt_Raise", ["deitado", "halteres"]],
    ["Reverse_Flyes", ["halteres"]],
    ["Reverse_Flyes_With_External_Rotation", ["halteres"]],
    ["Reverse_Machine_Flyes", ["maquina", "supinada"]],
    ["Seated_Bent-Over_Rear_Delt_Raise", ["curvado", "halteres", "sentado"]],
    ["Sled_Reverse_Flye", ["outro"]],
  ],
  desenvolvimento: [
    ["Alternating_Cable_Shoulder_Press", ["cabo", "unilateral"]],
    ["Barbell_Shoulder_Press", ["barra"]],
    ["Cable_Shoulder_Press", ["cabo"]],
    ["Dumbbell_One-Arm_Shoulder_Press", ["halteres", "unilateral"]],
    ["Dumbbell_Shoulder_Press", ["halteres"]],
    ["Kettlebell_Arnold_Press", ["arnold", "kettlebell"]],
    ["Leverage_Shoulder_Press", ["maquina"]],
    ["One-Arm_Kettlebell_Military_Press_To_The_Side", ["kettlebell", "lateral", "unilateral"]],
    ["Seated_Barbell_Military_Press", ["barra", "sentado"]],
    ["Seated_Cable_Shoulder_Press", ["cabo", "sentado"]],
    ["Shoulder_Press_-_With_Bands", ["elastico"]],
    ["Smith_Machine_Overhead_Shoulder_Press", ["maquina", "smith", "supinada"]],
    ["Standing_Military_Press", ["barra", "empe"]],
    ["Two-Arm_Kettlebell_Military_Press", ["kettlebell"]],
  ],
  elevacao_frontal: [
    ["Front_Cable_Raise", ["cabo"]],
    ["Front_Dumbbell_Raise", ["halteres"]],
    ["Front_Plate_Raise", ["anilha", "outro"]],
    ["Standing_Front_Barbell_Raise_Over_Head", ["barra", "empe"]],
  ],
  elevacao_lateral: [
    ["Bent_Over_Low-Pulley_Side_Lateral", ["cabo", "curvado", "lateral"]],
    ["Cable_Seated_Lateral_Raise", ["cabo", "sentado"]],
    ["Dumbbell_Lying_One-Arm_Rear_Lateral_Raise", ["deitado", "halteres", "unilateral"]],
    ["Dumbbell_Lying_Rear_Lateral_Raise", ["deitado", "halteres"]],
    ["Lateral_Raise_-_With_Bands", ["elastico"]],
    ["Lying_One-Arm_Lateral_Raise", ["deitado", "halteres", "unilateral"]],
    ["One-Arm_Incline_Lateral_Raise", ["halteres", "inclinado", "unilateral"]],
    ["One-Arm_Side_Laterals", ["halteres", "lateral", "unilateral"]],
    ["Seated_Side_Lateral_Raise", ["halteres", "lateral", "sentado"]],
    ["Side_Lateral_Raise", ["halteres", "lateral"]],
    ["Side_Laterals_to_Front_Raise", ["halteres", "lateral"]],
  ],
  elevacao_pernas: [
    ["Bent-Knee_Hip_Raise", ["livre"]],
    ["Flat_Bench_Lying_Leg_Raise", ["deitado", "livre"]],
    ["Hanging_Leg_Raise", ["livre", "suspenso"]],
    ["Knee_Hip_Raise_On_Parallel_Bars", ["outro"]],
    ["Leg_Lift", ["livre"]],
    ["Smith_Machine_Hip_Raise", ["maquina", "smith", "supinada"]],
  ],
  encolhimento: [
    ["Barbell_Shrug", ["barra"]],
    ["Barbell_Shrug_Behind_The_Back", ["barra"]],
    ["Cable_Shrugs", ["cabo"]],
    ["Calf-Machine_Shoulder_Shrug", ["maquina", "supinada"]],
    ["Clean_Shrug", ["barra"]],
    ["Dumbbell_Shrug", ["halteres"]],
    ["Leverage_Shrug", ["maquina"]],
    ["Middle_Back_Shrug", ["halteres"]],
    ["Smith_Machine_Behind_the_Back_Shrug", ["maquina", "smith", "supinada"]],
    ["Snatch_Shrug", ["barra"]],
  ],
  extensao_quadril: [
    ["Hip_Extension_with_Bands", ["elastico"]],
  ],
  extensora: [
    ["Leg_Extensions", ["maquina"]],
    ["Single-Leg_Leg_Extension", ["maquina", "unilateral"]],
  ],
  face_pull: [
    ["Face_Pull", ["cabo"]],
  ],
  flexao: [
    ["Clock_Push-Up", ["livre"]],
    ["Close-Grip_Push-Up_off_of_a_Dumbbell", ["fechada", "halteres", "livre"]],
    ["Decline_Push-Up", ["declinado", "outro"]],
    ["Handstand_Push-Ups", ["livre"]],
    ["Incline_Push-Up", ["inclinado", "livre"]],
    ["Incline_Push-Up_Close-Grip", ["fechada", "inclinado", "livre"]],
    ["Incline_Push-Up_Medium", ["inclinado", "livre"]],
    ["Incline_Push-Up_Reverse_Grip", ["inclinado", "livre", "supinada"]],
    ["Incline_Push-Up_Wide", ["inclinado", "livre"]],
    ["Plyo_Kettlebell_Pushups", ["kettlebell"]],
    ["Push_Up_to_Side_Plank", ["lateral", "livre"]],
    ["Push-Up_Wide", ["livre"]],
    ["Push-Ups_-_Close_Triceps_Position", ["livre"]],
    ["Push-Ups_With_Feet_Elevated", ["livre"]],
    ["Push-Ups_With_Feet_On_An_Exercise_Ball", ["bola"]],
    ["Pushups", ["livre"]],
    ["Pushups_Close_and_Wide_Hand_Positions", ["livre"]],
    ["Single-Arm_Push-Up", ["livre"]],
    ["Suspended_Push-Up", ["outro", "suspenso"]],
  ],
  flexora: [
    ["Ball_Leg_Curl", ["bola"]],
    ["Lying_Leg_Curls", ["deitado", "maquina"]],
    ["Seated_Leg_Curl", ["maquina", "sentado"]],
    ["Standing_Leg_Curl", ["empe", "maquina"]],
  ],
  good_morning: [
    ["Band_Good_Morning", ["elastico"]],
    ["Band_Good_Morning_Pull_Through", ["elastico"]],
    ["Good_Morning", ["barra"]],
    ["Good_Morning_off_Pins", ["barra"]],
    ["Hanging_Bar_Good_Morning", ["barra", "suspenso"]],
    ["Seated_Good_Mornings", ["barra", "sentado"]],
  ],
  hip_thrust: [
    ["Barbell_Hip_Thrust", ["barra"]],
  ],
  leg_press: [
    ["Leg_Press", ["maquina"]],
    ["Narrow_Stance_Leg_Press", ["maquina"]],
    ["Smith_Machine_Leg_Press", ["maquina", "smith", "supinada"]],
  ],
  panturrilha: [
    ["Barbell_Seated_Calf_Raise", ["barra", "sentado"]],
    ["Calf_Press", ["maquina"]],
    ["Calf_Press_On_The_Leg_Press_Machine", ["maquina", "supinada"]],
    ["Calf_Raise_On_A_Dumbbell", ["halteres"]],
    ["Calf_Raises_-_With_Bands", ["elastico"]],
    ["Donkey_Calf_Raises", ["outro"]],
    ["Dumbbell_Seated_One-Leg_Calf_Raise", ["halteres", "sentado", "unilateral"]],
    ["Rocking_Standing_Calf_Raise", ["barra", "empe"]],
    ["Seated_Calf_Raise", ["maquina", "sentado"]],
    ["Smith_Machine_Calf_Raise", ["maquina", "smith", "supinada"]],
    ["Smith_Machine_Reverse_Calf_Raises", ["maquina", "smith", "supinada"]],
    ["Standing_Barbell_Calf_Raise", ["barra", "empe"]],
    ["Standing_Calf_Raises", ["empe", "maquina"]],
    ["Standing_Dumbbell_Calf_Raise", ["empe", "halteres"]],
  ],
  paralelas: [
    ["Bench_Dips", ["livre"]],
    ["Dip_Machine", ["maquina", "supinada"]],
    ["Dips_-_Chest_Version", ["outro"]],
    ["Dips_-_Triceps_Version", ["livre"]],
    ["Jerk_Dip_Squat", ["barra"]],
    ["Parallel_Bar_Dip", ["outro"]],
    ["Ring_Dips", ["outro"]],
    ["Weighted_Bench_Dip", ["outro"]],
  ],
  ponte_gluteo: [
    ["Barbell_Glute_Bridge", ["barra"]],
    ["Single_Leg_Glute_Bridge", ["livre", "unilateral"]],
  ],
  prancha: [
    ["Plank", ["livre"]],
  ],
  pullover: [
    ["Bent-Arm_Barbell_Pullover", ["barra"]],
    ["Bent-Arm_Dumbbell_Pullover", ["halteres"]],
    ["Front_Raise_And_Pullover", ["barra"]],
    ["Straight-Arm_Dumbbell_Pullover", ["halteres"]],
    ["Wide-Grip_Decline_Barbell_Pullover", ["aberta", "barra", "declinado"]],
  ],
  puxada: [
    ["Close-Grip_Front_Lat_Pulldown", ["cabo", "fechada"]],
    ["Full_Range-Of-Motion_Lat_Pulldown", ["cabo"]],
    ["One_Arm_Lat_Pulldown", ["cabo", "unilateral"]],
    ["Rocky_Pull-Ups_Pulldowns", ["outro"]],
    ["Rope_Straight-Arm_Pulldown", ["cabo", "corda"]],
    ["Straight-Arm_Pulldown", ["cabo"]],
    ["Underhand_Cable_Pulldowns", ["cabo", "supinada"]],
    ["V-Bar_Pulldown", ["cabo"]],
    ["Wide-Grip_Lat_Pulldown", ["aberta", "cabo"]],
    ["Wide-Grip_Pulldown_Behind_The_Neck", ["aberta", "cabo"]],
  ],
  remada: [
    ["Alternating_Kettlebell_Row", ["kettlebell", "unilateral"]],
    ["Alternating_Renegade_Row", ["kettlebell", "unilateral"]],
    ["Bent_Over_Barbell_Row", ["barra", "curvado"]],
    ["Bent_Over_One-Arm_Long_Bar_Row", ["barra", "curvado", "unilateral"]],
    ["Bent_Over_Two-Arm_Long_Bar_Row", ["barra", "curvado"]],
    ["Bent_Over_Two-Dumbbell_Row", ["curvado", "halteres"]],
    ["Bent_Over_Two-Dumbbell_Row_With_Palms_In", ["curvado", "halteres"]],
    ["Bodyweight_Mid_Row", ["outro"]],
    ["Dumbbell_Incline_Row", ["halteres", "inclinado"]],
    ["Inverted_Row", ["outro"]],
    ["Inverted_Row_with_Straps", ["outro"]],
    ["Kneeling_High_Pulley_Row", ["cabo"]],
    ["Kneeling_Single-Arm_High_Pulley_Row", ["cabo"]],
    ["Leverage_High_Row", ["maquina"]],
    ["Leverage_Iso_Row", ["maquina"]],
    ["Low_Pulley_Row_To_Neck", ["cabo"]],
    ["Lying_Cambered_Barbell_Row", ["barra", "deitado"]],
    ["Lying_T-Bar_Row", ["cavalinho", "deitado", "maquina"]],
    ["One-Arm_Dumbbell_Row", ["halteres", "unilateral"]],
    ["One-Arm_Kettlebell_Row", ["kettlebell", "unilateral"]],
    ["One-Arm_Long_Bar_Row", ["barra", "unilateral"]],
    ["Shotgun_Row", ["cabo"]],
    ["Sled_Row", ["outro"]],
    ["Smith_Machine_Bent_Over_Row", ["curvado", "maquina", "smith", "supinada"]],
    ["Suspended_Row", ["outro", "suspenso"]],
    ["T-Bar_Row_with_Handle", ["barra", "cavalinho"]],
    ["Two-Arm_Kettlebell_Row", ["kettlebell"]],
  ],
  remada_alta: [
    ["Dumbbell_One-Arm_Upright_Row", ["halteres", "unilateral"]],
    ["Smith_Machine_One-Arm_Upright_Row", ["maquina", "smith", "supinada", "unilateral"]],
    ["Smith_Machine_Upright_Row", ["maquina", "smith", "supinada"]],
    ["Standing_Dumbbell_Upright_Row", ["empe", "halteres"]],
    ["Upright_Row_-_With_Bands", ["elastico"]],
  ],
  rosca: [
    ["Alternate_Hammer_Curl", ["halteres", "martelo", "unilateral"]],
    ["Alternate_Incline_Dumbbell_Curl", ["halteres", "inclinado", "unilateral"]],
    ["Barbell_Curl", ["barra"]],
    ["Barbell_Curls_Lying_Against_An_Incline", ["barra", "deitado", "inclinado"]],
    ["Cable_Hammer_Curls_-_Rope_Attachment", ["cabo", "corda", "martelo"]],
    ["Cable_Preacher_Curl", ["cabo", "scott"]],
    ["Cable_Wrist_Curl", ["cabo"]],
    ["Close-Grip_EZ_Bar_Curl", ["barra", "fechada"]],
    ["Close-Grip_EZ-Bar_Curl_with_Band", ["barraw", "fechada"]],
    ["Close-Grip_Standing_Barbell_Curl", ["barra", "empe", "fechada"]],
    ["Concentration_Curls", ["concentrada", "halteres"]],
    ["Cross_Body_Hammer_Curl", ["halteres", "martelo"]],
    ["Drag_Curl", ["barra"]],
    ["Dumbbell_Alternate_Bicep_Curl", ["halteres", "unilateral"]],
    ["Dumbbell_Bicep_Curl", ["halteres"]],
    ["Dumbbell_Prone_Incline_Curl", ["halteres", "inclinado"]],
    ["EZ-Bar_Curl", ["barraw"]],
    ["Finger_Curls", ["barra"]],
    ["Flexor_Incline_Dumbbell_Curls", ["halteres", "inclinado"]],
    ["Hammer_Curls", ["halteres", "martelo"]],
    ["High_Cable_Curls", ["cabo"]],
    ["Incline_Dumbbell_Curl", ["halteres", "inclinado"]],
    ["Incline_Hammer_Curls", ["halteres", "inclinado", "martelo"]],
    ["Incline_Inner_Biceps_Curl", ["halteres", "inclinado"]],
    ["Lying_Cable_Curl", ["cabo", "deitado"]],
    ["Lying_Close-Grip_Bar_Curl_On_High_Pulley", ["cabo", "deitado", "fechada"]],
    ["Lying_High_Bench_Barbell_Curl", ["barra", "deitado"]],
    ["Lying_Supine_Dumbbell_Curl", ["deitado", "halteres"]],
    ["Machine_Bicep_Curl", ["maquina", "supinada"]],
    ["Machine_Preacher_Curls", ["maquina", "scott", "supinada"]],
    ["One_Arm_Dumbbell_Preacher_Curl", ["halteres", "scott", "unilateral"]],
    ["Overhead_Cable_Curl", ["cabo"]],
    ["Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench", ["halteres"]],
    ["Palms-Down_Wrist_Curl_Over_A_Bench", ["barra"]],
    ["Palms-Up_Barbell_Wrist_Curl_Over_A_Bench", ["barra"]],
    ["Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench", ["halteres"]],
    ["Preacher_Curl", ["barra", "scott"]],
    ["Preacher_Hammer_Dumbbell_Curl", ["halteres", "martelo", "scott"]],
    ["Reverse_Barbell_Curl", ["barra"]],
    ["Reverse_Barbell_Preacher_Curls", ["barra", "barraw", "scott"]],
    ["Reverse_Cable_Curl", ["cabo"]],
    ["Reverse_Plate_Curls", ["anilha", "outro"]],
    ["Seated_Band_Hamstring_Curl", ["outro", "sentado"]],
    ["Seated_Close-Grip_Concentration_Barbell_Curl", ["barra", "concentrada", "fechada", "sentado"]],
    ["Seated_Dumbbell_Curl", ["halteres", "sentado"]],
    ["Seated_Dumbbell_Inner_Biceps_Curl", ["halteres", "sentado"]],
    ["Seated_Dumbbell_Palms-Down_Wrist_Curl", ["halteres", "sentado"]],
    ["Seated_Dumbbell_Palms-Up_Wrist_Curl", ["halteres", "sentado"]],
    ["Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl", ["halteres", "sentado", "unilateral"]],
    ["Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl", ["halteres", "sentado", "unilateral"]],
    ["Seated_Palm-Up_Barbell_Wrist_Curl", ["barra", "sentado"]],
    ["Seated_Palms-Down_Barbell_Wrist_Curl", ["barra", "sentado"]],
    ["Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl", ["cabo", "sentado"]],
    ["Spider_Curl", ["barraw"]],
    ["Standing_Biceps_Cable_Curl", ["cabo", "empe"]],
    ["Standing_Concentration_Curl", ["concentrada", "empe", "halteres"]],
    ["Standing_Dumbbell_Reverse_Curl", ["empe", "halteres"]],
    ["Standing_Inner-Biceps_Curl", ["empe", "halteres"]],
    ["Standing_One-Arm_Cable_Curl", ["cabo", "empe", "unilateral"]],
    ["Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench", ["empe", "halteres", "inclinado", "unilateral"]],
    ["Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl", ["barra", "empe"]],
    ["Two-Arm_Dumbbell_Preacher_Curl", ["halteres", "scott"]],
    ["Wide-Grip_Standing_Barbell_Curl", ["aberta", "barra", "empe"]],
    ["Zottman_Curl", ["halteres"]],
    ["Zottman_Preacher_Curl", ["halteres", "scott"]],
  ],
  rotacao_russa: [
    ["Cable_Russian_Twists", ["cabo"]],
    ["Russian_Twist", ["livre"]],
  ],
  stiff: [
    ["Romanian_Deadlift", ["barra"]],
    ["Romanian_Deadlift_from_Deficit", ["barra"]],
    ["Smith_Machine_Stiff-Legged_Deadlift", ["maquina", "smith", "supinada"]],
    ["Stiff_Leg_Barbell_Good_Morning", ["barra"]],
    ["Stiff-Legged_Barbell_Deadlift", ["barra"]],
    ["Stiff-Legged_Dumbbell_Deadlift", ["halteres"]],
    ["Wide_Stance_Stiff_Legs", ["barra"]],
  ],
  supino: [
    ["Barbell_Bench_Press_-_Medium_Grip", ["barra"]],
    ["Barbell_Guillotine_Bench_Press", ["barra"]],
    ["Barbell_Incline_Bench_Press_-_Medium_Grip", ["barra", "inclinado"]],
    ["Bench_Press_-_Powerlifting", ["barra"]],
    ["Bench_Press_-_With_Bands", ["elastico"]],
    ["Bench_Press_with_Chains", ["barra"]],
    ["Cable_Chest_Press", ["cabo"]],
    ["Close-Grip_Barbell_Bench_Press", ["barra", "fechada"]],
    ["Decline_Barbell_Bench_Press", ["barra", "declinado"]],
    ["Decline_Dumbbell_Bench_Press", ["declinado", "halteres"]],
    ["Dumbbell_Bench_Press", ["halteres"]],
    ["Dumbbell_Bench_Press_with_Neutral_Grip", ["halteres"]],
    ["Hammer_Grip_Incline_DB_Bench_Press", ["halteres", "inclinado", "martelo"]],
    ["Incline_Cable_Chest_Press", ["cabo", "inclinado"]],
    ["Leverage_Chest_Press", ["maquina"]],
    ["Leverage_Decline_Chest_Press", ["declinado", "maquina"]],
    ["Leverage_Incline_Chest_Press", ["inclinado", "maquina"]],
    ["Machine_Bench_Press", ["maquina", "supinada"]],
    ["One_Arm_Dumbbell_Bench_Press", ["halteres", "unilateral"]],
    ["Reverse_Band_Bench_Press", ["barra"]],
    ["Reverse_Triceps_Bench_Press", ["barra"]],
    ["Smith_Machine_Bench_Press", ["maquina", "smith", "supinada"]],
    ["Smith_Machine_Close-Grip_Bench_Press", ["fechada", "maquina", "smith", "supinada"]],
    ["Smith_Machine_Incline_Bench_Press", ["inclinado", "maquina", "smith", "supinada"]],
    ["Standing_Cable_Chest_Press", ["cabo", "empe"]],
    ["Wide-Grip_Barbell_Bench_Press", ["aberta", "barra"]],
    ["Wide-Grip_Decline_Barbell_Bench_Press", ["aberta", "barra", "declinado"]],
  ],
  terra: [
    ["Axle_Deadlift", ["outro"]],
    ["Barbell_Deadlift", ["barra"]],
    ["Cable_Deadlifts", ["cabo"]],
    ["Car_Deadlift", ["outro"]],
    ["Clean_Deadlift", ["barra"]],
    ["Deadlift_with_Bands", ["barra"]],
    ["Deadlift_with_Chains", ["barra"]],
    ["Deficit_Deadlift", ["barra"]],
    ["Kettlebell_One-Legged_Deadlift", ["kettlebell", "unilateral"]],
    ["Leverage_Deadlift", ["maquina"]],
    ["One-Arm_Side_Deadlift", ["barra", "lateral", "unilateral"]],
    ["Reverse_Band_Deadlift", ["barra"]],
    ["Reverse_Band_Sumo_Deadlift", ["barra", "sumo"]],
    ["Rickshaw_Deadlift", ["outro"]],
    ["Snatch_Deadlift", ["barra"]],
    ["Sumo_Deadlift", ["barra", "sumo"]],
    ["Sumo_Deadlift_with_Bands", ["barra", "sumo"]],
    ["Sumo_Deadlift_with_Chains", ["barra", "sumo"]],
    ["Trap_Bar_Deadlift", ["outro"]],
  ],
  triceps: [
    ["Body_Tricep_Press", ["livre"]],
    ["Cable_Incline_Pushdown", ["cabo", "inclinado"]],
    ["Cable_Incline_Triceps_Extension", ["cabo", "inclinado"]],
    ["Cable_Lying_Triceps_Extension", ["cabo", "deitado", "testa"]],
    ["Cable_One_Arm_Tricep_Extension", ["cabo", "unilateral"]],
    ["Cable_Rope_Overhead_Triceps_Extension", ["cabo", "corda"]],
    ["Decline_Dumbbell_Triceps_Extension", ["declinado", "halteres"]],
    ["Decline_EZ_Bar_Triceps_Extension", ["barra", "declinado"]],
    ["Dumbbell_One-Arm_Triceps_Extension", ["halteres", "unilateral"]],
    ["Dumbbell_Tricep_Extension_-Pronated_Grip", ["halteres", "pronada"]],
    ["EZ-Bar_Skullcrusher", ["barraw", "testa"]],
    ["Glute_Kickback", ["coice", "livre"]],
    ["Incline_Barbell_Triceps_Extension", ["barra", "inclinado"]],
    ["Kneeling_Cable_Triceps_Extension", ["cabo"]],
    ["Low_Cable_Triceps_Extension", ["cabo"]],
    ["Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head", ["barra", "deitado", "fechada"]],
    ["Lying_Close-Grip_Barbell_Triceps_Press_To_Chin", ["barra", "barraw", "deitado", "fechada", "supinada"]],
    ["Lying_Dumbbell_Tricep_Extension", ["deitado", "halteres"]],
    ["Lying_Triceps_Press", ["barraw", "deitado", "testa"]],
    ["Machine_Triceps_Extension", ["maquina", "supinada"]],
    ["One_Arm_Pronated_Dumbbell_Triceps_Extension", ["halteres", "pronada", "unilateral"]],
    ["One_Arm_Supinated_Dumbbell_Triceps_Extension", ["halteres", "supinada", "unilateral"]],
    ["One-Legged_Cable_Kickback", ["cabo", "coice", "unilateral"]],
    ["Reverse_Grip_Triceps_Pushdown", ["cabo", "supinada"]],
    ["Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension", ["curvado", "halteres", "sentado", "unilateral"]],
    ["Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension", ["curvado", "halteres", "sentado"]],
    ["Seated_Triceps_Press", ["halteres", "sentado"]],
    ["Sled_Overhead_Triceps_Extension", ["outro"]],
    ["Speed_Band_Overhead_Triceps", ["elastico"]],
    ["Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension", ["curvado", "empe", "halteres", "unilateral"]],
    ["Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension", ["curvado", "empe", "halteres"]],
    ["Standing_Dumbbell_Triceps_Extension", ["empe", "halteres"]],
    ["Standing_Low-Pulley_One-Arm_Triceps_Extension", ["cabo", "empe", "unilateral"]],
    ["Standing_One-Arm_Dumbbell_Triceps_Extension", ["empe", "halteres", "unilateral"]],
    ["Standing_Overhead_Barbell_Triceps_Extension", ["barra", "empe"]],
    ["Standing_Towel_Triceps_Extension", ["empe", "livre"]],
    ["Tricep_Dumbbell_Kickback", ["coice", "halteres"]],
    ["Triceps_Overhead_Extension_with_Rope", ["cabo", "corda"]],
    ["Triceps_Pushdown", ["cabo"]],
    ["Triceps_Pushdown_-_Rope_Attachment", ["cabo", "corda"]],
    ["Triceps_Pushdown_-_V-Bar_Attachment", ["cabo"]],
  ],
  voador: [
    ["Butterfly", ["maquina"]],
  ],
};
